version: "3.4"

networks:
  testcicd-backend:

services:
  postgres:
    container_name: postgres-testcicd
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - testcicd-backend

  pgadmin:
    container_name: pgadmin-testcicd
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: password
      PGADMIN_LISTEN_PORT: 8001
    ports:
      - "8001:8001"
    depends_on:
      - postgres
    networks:
      - testcicd-backend

  test-cicd:
    image: dihson103/test-cicd:latest
    container_name: test-cicd
    build:
      context: .
      dockerfile: src/WebApi/Dockerfile
    environment:
      - ConnectionStrings__DefaultConnection=Server=postgres:5432;User Id=postgres;Password=postgres;Database=testcicd
    ports:
      - 5000:8080
    depends_on:
      - postgres
    networks:
      - testcicd-backend

volumes:
  pgdata:
